export const FETCH_LIST_KANJI = 'FETCH_LIST_KANJI'
export const NEXT_PAGE_KANJI = 'NEXT_PAGE_KANJI'
export const SET_CURRENT_KANJI_DATA_WHEN_NEXT_PAGE = 'SET_CURRENT_KANJI_DATA_WHEN_NEXT_PAGE'
export const SET_CURRENT_KANJI_DATA_WHEN_PRE_PAGE = 'SET_CURRENT_KANJI_DATA_WHEN_PRE_PAGE'
export const SET_NEXT_PAGE_KANJI_DATA = 'SET_NEXT_PAGE_KANJI_DATA'
export const SET_PRE_PAGE_KANJI_DATA = 'SET_PRE_PAGE_KANJI_DATA'
export const SET_CURRENT_PAGE_KANJI_DATA = 'SET_CURRENT_PAGE_KANJI_DATA'
export const START_GET_DATA_KANJI = 'START_GET_DATA_KANJI'




